export const types = {
  openCreateDialog: "OPEN_CREATE_DIALOG",
  closeCreateDialog: "CLOSE_CREATE_DIALOG",
  openDeleteDialog: "OPEN_DELETE_DIALOG",
  closeDeleteDialog: "CLOSE_DELETE_DIALOG",
  openEditDialog: "OPEN_EDIT_DIALOG",
  closeEditDialog: "CLOSE_EDIT_DIALOG",
  errorTrue: "ERROR",
  errorFalse: "ERROR",
  getBusiness: "GET_BUSINESS",
  setActiveBusiness: "ACTIVE_BUSINESS",
  clearActiveBusiness: "CLEAR_ACTIVE",
  createBusiness: "BUSINESS_CREATED",
  deleteBusiness: "BUSINESS_DELETED",
  editingBusiness: "BUSINESS_EDITING",
  updateBusiness: "BUSINESS_UPDATED",
  getPeople: "GET_PEOPLE",
  setActivePerson: "ACTIVE_PERSON",
  clearActivePerson: "CLEAR_ACTIVE",
  createPerson: "PERSON_CREATED",
  deletePerson: "PERSON_DELETED",
  editingPerson: "PERSON_EDITING",
  updatePerson: "PESON_UPDATED",
  businessAssociated: "BUSINESS_ASSOCIATE",
};